### ISSUE TITLE
Cannot resolve dependency '../shared/ipc'

### ISSUE THREAD

**Issue by nash81** [satoshipay/solar#1314]
Hi,
While trying to run npm run dev  I get the following errors. Any help is highly appreciated.

/media/ubuntu/SSD/stellar/solar-0.28.1/src/SplashScreen/splash-screen.ts:1:25: Cannot resolve dependency '../shared/ipc' at '/media/ubuntu/SSD/stellar/solar-0.28.1/src/shared/ipc'
    at Resolver.resolve (/media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Resolver.js:71:17)
    at async Bundler.resolveAsset (/media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Bundler.js:433:18)
    at async Bundler.resolveDep (/media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Bundler.js:484:14)
    at async /media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Bundler.js:608:26
    at async Promise.all (index 2)
    at async Bundler.loadAsset (/media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 3)
    at async Bundler.loadAsset (/media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /media/ubuntu/SSD/stellar/solar-0.28.1/node_modules/parcel-bundler/src/Bundler.js:610:13
⚠️  Could not load source file "../src/index.ts" in source map of "../node_modules/stellar-sdk/lib/index.js".
⚠️  Could not load source file "../src/config.ts" in source map of "../node_modules/stellar-sdk/lib/config.js".
⚠️  Could not load source file "../src/horizon_api.ts" in source map of "../node_modules/stellar-sdk/lib/horizon_api.js".
⚠️  Could not load source file "../src/stellar_toml_resolver.ts" in source map of "../node_modules/stellar-sdk/lib/stellar_toml_resolver.js".
⚠️  Could not load source file "../src/federation_server.ts" in source map of "../node_modules/stellar-sdk/lib/federation_server.js".
⚠️  Could not load source file "../src/server_api.ts" in source map of "../node_modules/stellar-sdk/lib/server_api.js".
⚠️  Could not load source file "../src/account_response.ts" in source map of "../node_modules/stellar-sdk/lib/account_response.js".
⚠️  Could not load source file "../src/errors.ts" in source map of "../node_modules/stellar-sdk/lib/errors.js".
⚠️  Could not load source file "../src/server.ts" in source map of "../node_modules/stellar-sdk/lib/server.js".
⚠️  Could not load source file "../src/utils.ts" in source map of "../node_modules/stellar-sdk/lib/utils.js".
⚠️  Could not load source file "../src/horizon_axios_client.ts" in source map of "../node_modules/stellar-sdk/lib/horizon_axios_client.js".
⚠️  Could not load source file "../src/liquidity_pool_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/liquidity_pool_call_builder.js".
⚠️  Could not load source file "../src/effect_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/effect_call_builder.js".
⚠️  Could not load source file "../src/account_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/account_call_builder.js".
⚠️  Could not load source file "../src/assets_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/assets_call_builder.js".
⚠️  Could not load source file "../src/call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/call_builder.js".
⚠️  Could not load source file "../src/friendbot_builder.ts" in source map of "../node_modules/stellar-sdk/lib/friendbot_builder.js".
⚠️  Could not load source file "../src/operation_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/operation_call_builder.js".
⚠️  Could not load source file "../src/ledger_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/ledger_call_builder.js".
⚠️  Could not load source file "../src/offer_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/offer_call_builder.js".
⚠️  Could not load source file "../src/claimable_balances_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/claimable_balances_call_builder.js".
⚠️  Could not load source file "../src/orderbook_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/orderbook_call_builder.js".
⚠️  Could not load source file "../src/strict_send_path_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/strict_send_path_call_builder.js".
⚠️  Could not load source file "../src/transaction_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/transaction_call_builder.js".
⚠️  Could not load source file "../src/strict_receive_path_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/strict_receive_path_call_builder.js".
⚠️  Could not load source file "../src/trade_aggregation_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/trade_aggregation_call_builder.js".
⚠️  Could not load source file "../src/trades_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/trades_call_builder.js".
⚠️  Could not load source file "../src/payment_call_builder.ts" in source map of "../node_modules/stellar-sdk/lib/payment_call_builder.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@stellarguard/stellar-uri/build/module/index.js".
⚠️  Could not load source file "../../../src/lib/pay-stellar-uri.ts" in source map of "../node_modules/@stellarguard/stellar-uri/build/module/lib/pay-stellar-uri.js".
⚠️  Could not load source file "../../../src/lib/stellar-uri.ts" in source map of "../node_modules/@stellarguard/stellar-uri/build/module/lib/stellar-uri.js".
⚠️  Could not load source file "../../../src/lib/parse.ts" in source map of "../node_modules/@stellarguard/stellar-uri/build/module/lib/parse.js".
⚠️  Could not load source file "../../../src/lib/transaction-stellar-uri.ts" in source map of "../node_modules/@stellarguard/stellar-uri/build/module/lib/transaction-stellar-uri.js".
⚠️  Could not load source file "../../../src/lib/replacement.ts" in source map of "../node_modules/@stellarguard/stellar-uri/build/module/lib/replacement.js".
⚠️  Could not load source file "../../src/index.ts" in source map of "../node_modules/@stellarguard/txrep/build/module/index.js".

**Comment by ebma** [comment]
Hey there. Have you tried if this also happens on a fresh clone of Solar? I noticed that when I fresh clone the repo, npm install the modules and `npm run dev` the electron window was closing automatically which is why I updated the dependency in #1316 so this should be fixed now. But it seems that your symlink to `./shared/ipc` is broken so maybe a fresh clone helps.

**Comment by nash81** [comment]
Ok, let me try.
What version of Node do you recommend.
and I am building on windows could that be the reason behind symlink being broken

**Comment by ebma** [comment]
I'm using node version `v16.13.0` but I think older versions should also work. And yes that you are using windows could indeed be the reason for this. I assumed you were using Ubuntu because you mentioned that. Are you using the linux subsystem for windows? I found a [StackOverflow post](https://stackoverflow.com/a/59761201) that might be helpful for you, you could try the steps mentioned there to fix the symlinks. Let me know if this worked for you.
