### ISSUE TITLE
Windows auto-updater broken

### ISSUE THREAD

**Issue by andywer** [satoshipay/solar#938]
As reported by Alex:

After clicking on the update button on the all-accounts view, the update seems to start but fails immediately with the error message "Can not find Squirrel" (red error toast).

Stack trace:

```
app.41304f27.js:271 Error: Can not find Squirrel
    at AutoUpdater.emitError (C:\Users\alex\AppData\Local\Programs\satoshipay-stellar-wallet\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:70:24)
    at AutoUpdater.checkForUpdates (C:\Users\alex\AppData\Local\Programs\satoshipay-stellar-wallet\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:41:19)
    at startUpdating (C:\Users\alex\AppData\Local\Programs\satoshipay-stellar-wallet\resources\app.asar\electron\lib\updater.js:74:28)
    at startUpdatingWithoutInfo (C:\Users\alex\AppData\Local\Programs\satoshipay-stellar-wallet\resources\app.asar\electron\lib\updater.js:69:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at async EventEmitter.<anonymous> (C:\Users\alex\AppData\Local\Programs\satoshipay-stellar-wallet\resources\app.asar\electron\lib\ipc.js:33:28)
d @ app.41304f27.js:271
```

**Comment by andywer** [comment]
Not sure yet if this is an isolated incident or if it affects all Windows installations. Hopefully not…
